// Product categories with icons
export const categories = [
  { id: 1, name: "All Products", icon: "" },
  { id: 2, name: "Anti-Diabetic", icon: "" },
  { id: 3, name: "Anti-Hypertensive", icon: "" },
  { id: 4, name: "Dyslipidemia", icon: "" },
  { id: 5, name: "Antiplatelet", icon: "" },
  { id: 6, name: "PPI's", icon: "" },
  { id: 7, name: "Anti-Infective", icon: "" },
  { id: 8, name: "Supplements", icon: "" },
]

// Complete product data
export const allProducts = [
  { id: 1, name: "Sitavast-D 10/100", composition: "Dapagliflozin 10mg + Sitagliptin Phosphate 100mg", form: "Tablet", strength: "10/100 mg", category: "Anti-Diabetic", image: "/Cadvast-EZ-10.png" },
  { id: 2, name: "Sitavast-M", composition: "Sitagliptin Phosphate 50mg + Metformin Hydrochloride", form: "Tablet", strength: "50/500 mg", category: "Anti-Diabetic", image: "/Cadvast-EZ-10.png" },
  { id: 3, name: "Sitavast-DM 10/100", composition: "Dapagliflozin 10mg + Sitagliptin 50mg + Metformin 1000mg", form: "Tablet", strength: "10/50/1000 mg", category: "Anti-Diabetic", image: "/Cadvast-EZ-10.png" },
  { id: 4, name: "LINAFLOZ-5/10", composition: "Linagliptin 5mg + Dapagliflozin 10mg", form: "Tablet", strength: "5/10 mg", category: "Anti-Diabetic", image: "/Cadvast-EZ-10.png" },
  { id: 5, name: "Glimberry-M1", composition: "Glimepiride + Metformin", form: "Tablet", strength: "1/500 mg", category: "Anti-Diabetic", image: "/Cadvast-EZ-10.png" },
  { id: 6, name: "Glimberry-M2", composition: "Glimepiride + Metformin", form: "Tablet", strength: "2/500 mg", category: "Anti-Diabetic", image: "/Cadvast-EZ-10.png" },
  { id: 7, name: "HBTEL 40", composition: "Telmisartan", form: "Tablet", strength: "40 mg", category: "Anti-Hypertensive", image: "/Cadvast-EZ-10.png" },
  { id: 8, name: "HBTEL AM 40", composition: "Telmisartan + Amlodipine", form: "Tablet", strength: "40/5 mg", category: "Anti-Hypertensive", image: "/Cadvast-EZ-10.png" },
  { id: 9, name: "HBTEL LN 40", composition: "Telmisartan + Lisinopril", form: "Tablet", strength: "40/10 mg", category: "Anti-Hypertensive", image: "/Cadvast-EZ-10.png" },
  { id: 10, name: "Bisoberry 2.5", composition: "Bisoprolol", form: "Tablet", strength: "2.5 mg", category: "Anti-Hypertensive", image: "/Cadvast-EZ-10.png" },
  { id: 11, name: "Bisoberry T 2.5", composition: "Bisoprolol + Telmisartan", form: "Tablet", strength: "2.5/40 mg", category: "Anti-Hypertensive", image: "/Cadvast-EZ-10.png" },
  { id: 12, name: "Bisoberry T 5", composition: "Bisoprolol + Telmisartan", form: "Tablet", strength: "5/40 mg", category: "Anti-Hypertensive", image: "/Cadvast-EZ-10.png" },
  { id: 13, name: "Cadvast-10", composition: "Rosuvastatin Calcium", form: "Tablet", strength: "10 mg", category: "Dyslipidemia", image: "/Cadvast-EZ-10.png" },
  { id: 14, name: "Cadvast-20", composition: "Rosuvastatin Calcium", form: "Tablet", strength: "20 mg", category: "Dyslipidemia", image: "/Cadvast-EZ-10.png" },
  { id: 15, name: "Cadvast-40", composition: "Rosuvastatin Calcium", form: "Tablet", strength: "40 mg", category: "Dyslipidemia", image: "/Cadvast-EZ-10.png" },
  { id: 16, name: "Cadvast CV-10", composition: "Rosuvastatin + Clopidogrel", form: "Tablet", strength: "10/75 mg", category: "Dyslipidemia", image: "/Cadvast-EZ-10.png" },
  { id: 17, name: "Cadvast CV-20", composition: "Rosuvastatin + Clopidogrel", form: "Tablet", strength: "20/75 mg", category: "Dyslipidemia", image: "/Cadvast-EZ-10.png" },
  { id: 18, name: "Cadvast ASP-10", composition: "Rosuvastatin + Aspirin", form: "Tablet", strength: "10/150 mg", category: "Dyslipidemia", image: "/Cadvast-EZ-10.png" },
  { id: 19, name: "Cloberry-75", composition: "Clopidogrel Bisulphate", form: "Tablet", strength: "75 mg", category: "Antiplatelet", image: "/Cadvast-EZ-10.png" },
  { id: 20, name: "Pentagard 40", composition: "Pantoprazole", form: "Tablet", strength: "40 mg", category: "PPI's", image: "/Cadvast-EZ-10.png" },
  { id: 21, name: "Pentagard DSR", composition: "Pantoprazole", form: "Delayed-release Capsule", strength: "40 mg", category: "PPI's", image: "/Cadvast-EZ-10.png" },
  { id: 22, name: "Razed DSR", composition: "Rabeprazole", form: "Prolonged-release Capsule", strength: "20 mg", category: "PPI's", image: "/Cadvast-EZ-10.png" },
  { id: 23, name: "Amoxberry-625", composition: "Amoxicillin + Clavulanic Acid", form: "Tablet", strength: "500/125 mg", category: "Anti-Infective", image: "/Cadvast-EZ-10.png" },
  { id: 24, name: "Cefrophat-500", composition: "Cefuroxime Axetil", form: "Tablet", strength: "500 mg", category: "Anti-Infective", image: "/Cadvast-EZ-10.png" },
  { id: 25, name: "Tab Apserra", composition: "Aceclofenac + Paracetamol + Serratiopeptidase", form: "Tablet", strength: "100/500/10 mg", category: "Anti-Infective", image: "/Cadvast-EZ-10.png" },
  { id: 26, name: "Vitzee Tablets", composition: "Antioxidant + Multivitamin", form: "Tablet", strength: "Complex", category: "Supplements", image: "/Cadvast-EZ-10.png" },
  { id: 27, name: "Vitzee D3 60K", composition: "Cholecalciferol", form: "Tablet", strength: "60000 IU", category: "Supplements", image: "/Cadvast-EZ-10.png" },
  { id: 28, name: "Cadcure", composition: "Methylcobalamin + Alpha Lipoic Acid + Folic Acid + Vitamin D3", form: "Capsule", strength: "Complex", category: "Supplements", image: "/Cadvast-EZ-10.png" },
  { id: 29, name: "Preberry-NT", composition: "Pregabalin + Methylcobalamin + Nortriptyline + Folic Acid", form: "Capsule", strength: "Complex", category: "Supplements", image: "/Cadvast-EZ-10.png" },
  { id: 30, name: "Calvance D", composition: "Calcium Carbonate + Vitamin D3", form: "Tablet", strength: "500/400 IU", category: "Supplements", image: "/Cadvast-EZ-10.png" },
  { id: 31, name: "Calvance-DM", composition: "Calcium + Vitamin D3 + Methylcobalamin", form: "Tablet", strength: "500/400/1.5 mcg", category: "Supplements", image: "/Cadvast-EZ-10.png" },
  { id: 32, name: "Cosfur XT", composition: "Ferrous Ascorbate + Folic Acid + Zinc", form: "Tablet", strength: "Complex", category: "Supplements", image: "/Cadvast-EZ-10.png" },
]
