// Product categories with icons
export const categories = [
  { id: 1, name: "All Products", icon: "" },
  { id: 2, name: "Anti-Diabetic", icon: "" },
  { id: 3, name: "Anti-Hypertensive", icon: "" },
  { id: 4, name: "Dyslipidemia", icon: "" },
  { id: 5, name: "Antiplatelet", icon: "" },
  { id: 6, name: "PPI's", icon: "" },
  { id: 7, name: "Anti-Infective", icon: "" },
  { id: 8, name: "Supplements", icon: "" },
]

// Complete product data
export const allProducts = [
  { id: 1, name: "Sitavast-D 10/100", composition: "Dapagliflozin 10mg + Sitagliptin Phosphate 100mg", form: "Tablet", strength: "10/100 mg", category: "Anti-Diabetic", image: "/Sitavast-D-10-100.png", rightImage: "public/Sitavast-D-10-100.png" },
  { id: 2, name: "Sitavast-M", composition: "Sitagliptin Phosphate 50mg + Metformin Hydrochloride", form: "Tablet", strength: "50/500 mg", category: "Anti-Diabetic", image:"/Sitavast-M.png", rightImage: "/Sitavast-M.png" },
  { id: 3, name: "Sitavast-DM 10/100", composition: "Dapagliflozin 10mg + Sitagliptin 50mg + Metformin 1000mg", form: "Tablet", strength: "10/50/1000 mg", category: "Anti-Diabetic", image: "/Sitavast-DM-10-100.png", rightImage: "/Sitavast-DM-10-100.png" },
  { id: 4, name: "LINAFLOZ-5/10", composition: "Linagliptin 5mg + Dapagliflozin 10mg", form: "Tablet", strength: "5/10 mg", category: "Anti-Diabetic", image: "/LINAFLOZ-5-10.png", rightImage: "/LINAFLOZ-5-10.png" },
  { id: 5, name: "Glimberry-M1/M2", composition: "Glimepiride + Metformin HCI 500mg Tablets", form: "Tablet", strength: "1-2/500 mg", category: "Anti-Diabetic", image: "/Glimbery-m1-m2.png", rightImage: "/Glimbery-m1-m2.png" },
  { id: 6, name: "Glimberry-M1/M2 Forte", composition: "Glimepiride + Metformin HCI 1000mg Tablets", form: "Tablet", strength: "`1-2/1000 mg", category: "Anti-Diabetic", image: "/Glimbery-m1-m2-forte.png", rightImage: "/Glimbery-m1-m2-forte.png" },
  { id: 33, name: "Glimberry-MP1/MP2", composition: "Glimepiride 1/2mg + Pioglitazone 15mg + Metformin 500mg SR Tablets", form: "Tablet", strength: "2/15/500 mg", category: "Anti-Diabetic", image: "/Glimbery-mp1-mp2.png", rightImage: "/Glimbery-mp1-mp2.png" },
  { id: 34, name: "Glimberry-MV1/MV2", composition: "Glimepiride 1/2mg + Metformin 500mg SR + Voglibose 0.2/0.3 mg Tablets", form: "Tablet", strength: "2/500/0.3 mg", category: "Anti-Diabetic", image: "/Glimbery-mv1-mv2.png", rightImage: "/Glimbery-mv1-mv2.png" },
  { id: 7, name: "HBTEL 40", composition: "Telmisartan", form: "Tablet", strength: "40 mg", category: "Anti-Hypertensive", image: "/HBTEL-40.png", rightImage: "/HBTEL-40.png" },
  { id: 8, name: "HBTEL AM 40", composition: "Telmisartan + Amlodipine", form: "Tablet", strength: "40/5 mg", category: "Anti-Hypertensive", image: "/HBTEL-AM-40.png", rightImage: "/HBTEL-AM-40.png" },
  { id: 9, name: "HBTEL LN 40", composition: "Telmisartan + Clinidipine", form: "Tablet", strength: "40/10 mg", category: "Anti-Hypertensive", image: "/HBTEL-LN-40.png", rightImage: "/HBTEL-LN-40.png" },
  { id: 10, name: "Bisoberry 2.5", composition: "Bisoprolol", form: "Tablet", strength: "2.5 mg", category: "Anti-Hypertensive", image: "/Bisoberry-2-5.png", rightImage: "/Bisoberry-2-5.png" },
  { id: 11, name: "Bisoberry T 2.5/5", composition: "Bisoprolol + Telmisartan", form: "Tablet", strength: "2.5/40 mg", category: "Anti-Hypertensive", image: "/Bisoberry-T-2-5.png", rightImage: "/Bisoberry-T-2-5.png" },
  { id: 12, name: "HBTEL CT", composition: "Bisoprolol + Chlorthalidone 6.2Smg Tablets", form: "Tablet", strength: "5/6.25 mg", category: "Anti-Hypertensive", image: "/HBTEL-CT.png", rightImage: "/HBTEL-CT.png" },
  { id: 35, name: "HBTEL TRIO", composition: "Bisoprolol + Chlorthalidone + Clinidipine Tablets", form: "Tablet", strength: "5/6.25/40 mg", category: "Anti-Hypertensive", image: "/HBTEL-Trio.png", rightImage: "/HBTEL-Trio.png" },
  { id: 13, name: "Cadvast-10", composition: "Rosuvastatin Calcium", form: "Tablet", strength: "10 mg", category: "Dyslipidemia", image: "/Cadvast-10-20-40.png", rightImage: "/Cadvast-10-20-40.png" },
  { id: 14, name: "Cadvast-20", composition: "Rosuvastatin Calcium", form: "Tablet", strength: "20 mg", category: "Dyslipidemia", image: "/Cadvast-10-20-40.png", rightImage: "/Cadvast-10-20-40.png" },
  { id: 15, name: "Cadvast-40", composition: "Rosuvastatin Calcium", form: "Tablet", strength: "40 mg", category: "Dyslipidemia", image: "/Cadvast-10-20-40.png", rightImage: "/Cadvast-10-20-40.png" },
  { id: 16, name: "Cadvast CV-10", composition: "Rosuvastatin + Clopidogrel", form: "Tablet", strength: "10/75 mg", category: "Dyslipidemia", image: "/Cadvast-cv-10-20.png", rightImage: "/Cadvast-cv-10-20.png" },
  { id: 17, name: "Cadvast CV-20", composition: "Rosuvastatin + Clopidogrel", form: "Tablet", strength: "20/75 mg", category: "Dyslipidemia", image: "/Cadvast-cv-10-20.png", rightImage: "/Cadvast-cv-10-20.png" },
  { id: 18, name: "Cadvast ASP-10", composition: "Rosuvastatin + Aspirin", form: "Tablet", strength: "10/150 mg", category: "Dyslipidemia", image: "/Cadvast-asp.png", rightImage: "/Cadvast-asp.png" },
  { id: 36, name: "Cadvast GOLD 10/20/75", composition: "Rosuvastatin + Clopidogrel+ Aspirin", form: "Tablet", strength: "10/20/75 mg", category: "Dyslipidemia", image: "/Cadvast-gold.png", rightImage: "/Cadvast-gold.png" },
  { id: 19, name: "Cloberry-75", composition: "Clopidogrel Bisulphate", form: "Tablet", strength: "75 mg", category: "Antiplatelet", image: "/cloberry.png", rightImage: "/cloberry.png" },
  { id: 21, name: "Pentagard DSR", composition: "Pantoprazole", form: "Delayed-release Capsule", strength: "40 mg", category: "PPI's", image: "/Pentagard-dsr.png", rightImage: "/Pentagard-dsr.png" },
  { id: 22, name: "Razed DSR", composition: "Rabeprazole", form: "Prolonged-release Capsule", strength: "20 mg", category: "PPI's", image: "/Razed.png", rightImage: "/Razed.png" },
  { id: 23, name: "Amoxberry-625", composition: "Amoxicillin + Clavulanic Acid", form: "Tablet", strength: "500/125 mg", category: "Anti-Infective", image: "/Amoxberry.png", rightImage: "/Amoxberry.png" },
  { id: 24, name: "Cefropath-500", composition: "Cefuroxime Axetil", form: "Tablet", strength: "500 mg", category: "Anti-Infective", image: "/Cefropath.png", rightImage: "/Cefropath.png" },
  { id: 25, name: "Tab Apserra", composition: "Aceclofenac + Paracetamol + Serratiopeptidase", form: "Tablet", strength: "100/500/10 mg", category: "Anti-Infective", image: "/Apserra.png", rightImage: "/Apserra.png" },
  { id: 26, name: "Vitzee Tablets", composition: "Antioxidant + Multivitamin", form: "Tablet", strength: "Complex", category: "Supplements", image: "/Vitzee.png", rightImage: "/Vitzee.png" },
  { id: 27, name: "Vitzee D3 60K", composition: "Cholecalciferol", form: "Tablet", strength: "60000 IU", category: "Supplements", image: "/Vitzee-D3-60K.png", rightImage: "/Vitzee-D3-60K.png" },
  { id: 28, name: "Cadcure", composition: "Methylcobalamin + Alpha Lipoic Acid + Folic Acid + Vitamin D3", form: "Capsule", strength: "Complex", category: "Supplements", image: "/Cadcure.png", rightImage: "/Cadcure.png" },
  { id: 29, name: "Preberry-NT", composition: "Pregabalin + Methylcobalamin + Nortriptyline + Folic Acid", form: "Capsule", strength: "Complex", category: "Supplements", image: "/Preberry-NT.png", rightImage: "/Preberry-NT.png" },
  { id: 30, name: "Calvance D", composition: "Calcium Carbonate + Vitamin D3", form: "Tablet", strength: "500/400 IU", category: "Supplements", image: "/Calvance-D.png", rightImage: "/Calvance-D.png" },
  { id: 31, name: "Calvance-DM", composition: "Calcium + Vitamin D3 + Methylcobalamin", form: "Tablet", strength: "500/400/1.5 mcg", category: "Supplements", image: "/Calvance-DM.png", rightImage: "/Calvance-DM.png" },
  { id: 32, name: "Cosfur XT", composition: "Ferrous Ascorbate + Folic Acid + Zinc", form: "Tablet", strength: "Complex", category: "Supplements", image: "/Cosfur-XT.png", rightImage: "/Cosfur-XT.png" },
]
