// Product categories with icons
export const categories = [
  { id: 1, name: "All Products", icon: "" },
  { id: 2, name: "Anti-Diabetic", icon: "" },
  { id: 3, name: "Anti-Hypertensive", icon: "" },
  { id: 4, name: "Dyslipidemia", icon: "" },
  { id: 5, name: "Antiplatelet", icon: "" },
  { id: 6, name: "PPI's", icon: "" },
  { id: 7, name: "Anti-Infective", icon: "" },
  { id: 8, name: "Supplements", icon: "" },
]

// Complete product data
export const allProducts = [
  { id: 1, name: "Sitavast-D 10/100", composition: "Dapagliflozin 10mg + Sitagliptin Phosphate 100mg Tablets", form: "Tablet", strength: "10/100 mg", category: "Anti-Diabetic", image: "/Sitavast-D-10-100.jpg", rightImage: "public/Sitavast-D-10-100.jpg" },
  { id: 2, name: "Sitavast-M", composition: "Sitagliptin Phosphate 50mg + Metformin Hydrochloride Tablets", form: "Tablet", strength: "50/500 mg", category: "Anti-Diabetic", image:"/Sitavast-M.jpg", rightImage: "/Sitavast-M.jpg" },
  { id: 3, name: "Sitavast-DM 10/100/1000", composition: "Dapagliflozin 10mg + Sitagliptin 100mg + Metformin 1000mg", form: "Tablet", strength: "10/50/1000 mg", category: "Anti-Diabetic", image: "/Sitavast-DM-10-100.jpg", rightImage: "/Sitavast-DM-10-100.jpg" },
  { id: 45, name: "Sitavast-DM 10/100/500", composition: "Dapagliflozin 10mg + Sitagliptin 100mg + Metformin 500mg", form: "Tablet", strength: "10/50/500 mg", category: "Anti-Diabetic", image: "/Sitavast-DM-10-100-500.jpg", rightImage: "/Sitavast-DM-10-100-500.jpg" },
  { id: 4, name: "LINAFLOZ-5/10", composition: "Linagliptin 5mg + Dapagliflozin 10mg", form: "Tablet", strength: "5/10 mg", category: "Anti-Diabetic", image: "/LINAFLOZ-5-10.jpg", rightImage: "/LINAFLOZ-5-10.jpg" },
  { id: 5, name: "Glimberry-M1", composition: "Glimepiride HCL 1mg + Metformin HCL 500mg Tablets", form: "Tablet", strength: "1/500 mg", category: "Anti-Diabetic", image: "/Glimbery-m1.jpg", rightImage: "/Glimbery-m1.jpg" },
  { id: 36, name: "Glimberry-M2", composition: "Glimepiride HCL 2mg+ Metformin HCL 500mg Tablets", form: "Tablet", strength: "2/500 mg", category: "Anti-Diabetic", image: "/Glimbery-m2.jpg", rightImage: "/Glimbery-m2.jpg" },
  { id: 6, name: "Glimberry-M1 Forte", composition: "Glimepiride + Metformin HCL 1000mg Tablets", form: "Tablet", strength: "1/1000 mg", category: "Anti-Diabetic", image: "/Glimbery-m1-forte.jpg", rightImage: "/Glimbery-m1-forte.jpg" },
  { id: 37, name: "Glimberry-M2 Forte", composition: "Glimepiride + Metformin HCL 1000mg Tablets", form: "Tablet", strength: "2/1000 mg", category: "Anti-Diabetic", image: "/Glimbery-m2-forte.jpg", rightImage: "/Glimbery-m2-forte.jpg" },
  { id: 33, name: "Glimberry-MP1", composition: "Glimepiride 1mg + Pioglitazone 15mg + Metformin 500mg SR Tablets", form: "Tablet", strength: "1/15/500 mg", category: "Anti-Diabetic", image: "/Glimbery-mp1.jpg", rightImage: "/Glimbery-mp1.jpg" },
  { id: 38, name: "Glimberry-MP2", composition: "Glimepiride 2mg + Pioglitazone 15mg + Metformin 500mg SR Tablets", form: "Tablet", strength: "2/15/500 mg", category: "Anti-Diabetic", image: "/Glimbery-mp2.jpg", rightImage: "/Glimbery-mp2.jpg" },
  { id: 34, name: "Glimberry-MV1", composition: "Glimepiride 1mg + Metformin 500mg SR + Voglibose 0.2 mg Tablets", form: "Tablet", strength: "1/500/0.3 mg", category: "Anti-Diabetic", image: "/Glimbery-mv1.jpg", rightImage: "/Glimbery-mv1.jpg" },
  { id: 39, name: "Glimberry-MV2", composition: "Glimepiride 2mg + Metformin 500mg SR + Voglibose 0.2 mg Tablets", form: "Tablet", strength: "2/500/0.2 mg", category: "Anti-Diabetic", image: "/Glimbery-mv2.jpg", rightImage: "/Glimbery-mv2.jpg" },
  { id: 7, name: "HBTEL 40", composition: "Telmisartan 40 mg", form: "Tablet", strength: "40 mg", category: "Anti-Hypertensive", image: "/HBTEL-40.jpg", rightImage: "/HBTEL-40.jpg" },
  { id: 8, name: "HBTEL AM 40", composition: "Telmisartan 40 mg + Amlodipine 5 mg", form: "Tablet", strength: "40/5 mg", category: "Anti-Hypertensive", image: "/HBTEL-AM-40.jpg", rightImage: "/HBTEL-AM-40.jpg" },
  { id: 9, name: "HBTEL LN 40", composition: "Telmisartan 40 mg + Clinidipine 10 mg", form: "Tablet", strength: "40/10 mg", category: "Anti-Hypertensive", image: "/HBTEL-LN-40.png", rightImage: "/HBTEL-LN-40.png" },
  { id: 10, name: "Bisoberry 2.5", composition: "Bisoprolol Fumarate Tablets 2.5 mg", form: "Tablet", strength: "2.5 mg", category: "Anti-Hypertensive", image: "/Bisoberry-2.5.jpg", rightImage: "/Bisoberry-2.5.jpg" },
  { id: 41, name: "Bisoberry 5", composition: "Bisoprolol Fumarate Tablets 5 mg", form: "Tablet", strength: "5 mg", category: "Anti-Hypertensive", image: "/Bisoberry-5.jpg", rightImage: "/Bisoberry-5.jpg" },
  { id: 11, name: "Bisoberry T 5", composition: "Bisoprolol Fumarate 5 mg + Telmisartan 40 mg Tablets", form: "Tablet", strength: "5/40 mg", category: "Anti-Hypertensive", image: "/Bisoberry-T-5.jpg", rightImage: "/Bisoberry-T-5.jpg" },
  { id: 40, name: "Bisoberry T 2.5", composition: "Bisoprolol Fumarate 2.5 mg & Telmisartan 40 mg Tablets", form: "Tablet", strength: "2.5/40 mg", category: "Anti-Hypertensive", image: "/Bisoberry-T-2.5.jpg", rightImage: "/Bisoberry-T-2.5.jpg" },
  { id: 12, name: "HBTEL CT", composition: "Telmisartan 40 mg + Chlorthalidone 6.25 mg", form: "Tablet", strength: "40/6.25 mg", category: "Anti-Hypertensive", image: "/HBTEL-CT.jpg", rightImage: "/HBTEL-CT.jpg" },
  { id: 35, name: "HBTEL TRIO", composition: "Telmisartan 40 mg + Chlorthalidone 6.25 mg + Clinidipine 10 mg Tablets", form: "Tablet", strength: "40/6.25/10 mg", category: "Anti-Hypertensive", image: "/HBTEL-Trio.jpg", rightImage: "/HBTEL-Trio.jpg" },
  { id: 42, name: "Cadvast-EZ 10", composition: "Rosuvastatin Calcium and Ezetimibe 10 mg Tablets", form: "Tablet", strength: "10 mg", category: "Dyslipidemia", image: "/Cadvast-EZ-10.png", rightImage: "/Cadvast-EZ-10.png" },
  { id: 43, name: "Cadvast-EZ 20", composition: "Rosuvastatin Calcium and Ezetimibe 20 mg Tablets ", form: "Tablet", strength: "20 mg", category: "Dyslipidemia", image: "/Cadvast-EZ-20.jpg", rightImage: "/Cadvast-EZ-20.jpg" },
  { id: 48, name: "Cadvast F-10/160 ", composition: "Rosuvastatin 10 mg +Fenofibrate 160 mg Tablets", form: "Tablet", strength: "10/75 mg", category: "Dyslipidemia", image: "/Cadvast-F-10.jpg", rightImage: "/Cadvast-F-10.jpg" },
  { id: 13, name: "Cadvast-10", composition: "Rosuvastatin Tablets IP 10 mg", form: "Tablet", strength: "10 mg", category: "Dyslipidemia", image: "/Cadvast-10.jpg", rightImage: "/Cadvast-10.jpg" },
  { id: 14, name: "Cadvast-20", composition: "Rosuvastatin Tablets IP 20 mg", form: "Tablet", strength: "20 mg", category: "Dyslipidemia", image: "/Cadvast-20.jpg", rightImage: "/Cadvast-20.jpg" },
  { id: 15, name: "Cadvast-40", composition: "Rosuvastatin Tablets IP 40 mg", form: "Tablet", strength: "40 mg", category: "Dyslipidemia", image: "/Cadvast-40.jpg", rightImage: "/Cadvast-40.jpg" },
  { id: 16, name: "Cadvast CV-10", composition: "Rosuvastatin 10 mg + Clopidogrel 75 mg", form: "Capsule", strength: "10/75 mg", category: "Dyslipidemia", image: "/Cadvast-cv-10.jpg", rightImage: "/Cadvast-cv-10.jpg" },
  { id: 17, name: "Cadvast CV-20", composition: "Rosuvastatin 20 mg + Clopidogrel 75 mg", form: "Capsule", strength: "20/75 mg", category: "Dyslipidemia", image: "/Cadvast-cv-20.jpg", rightImage: "/Cadvast-cv-20.jpg" },
  { id: 18, name: "Cadvast ASP-10", composition: "Rosuvastatin 10 mg + Aspirin 75 mg", form: "Capsule", strength: "10/75 mg", category: "Dyslipidemia", image: "/Cadvast-asp.jpg", rightImage: "/Cadvast-asp.jpg" },
  { id: 47, name: "Cadvast ASP-20", composition: "Rosuvastatin 20 mg + Aspirin 75 mg", form: "Capsule", strength: "20/75 mg", category: "Dyslipidemia", image: "/Cadvast-asp-20.jpg", rightImage: "/Cadvast-asp-20.jpg" },
  { id: 49, name: "Cadvast GOLD 10", composition: "Rosuvastatin 10 mg + Clopidogrel 20 mg + Aspirin(EC) 75 mg", form: "Capsule", strength: "10/20/75 mg", category: "Dyslipidemia", image: "/Cadvast-gold-10.jpg", rightImage: "/Cadvast-gold-10.jpg" },
  { id: 44, name: "Cadvast GOLD 20", composition: "Rosuvastatin 20 mg + Clopidogrel 20 mg + Aspirin(EC) 75 mg", form: "Capsule", strength: "20/20/75 mg", category: "Dyslipidemia", image: "/Cadvast-gold-20.jpg", rightImage: "/Cadvast-gold-20.jpg" },
  { id: 19, name: "Cloberry-75", composition: "Clopidogrel Bisulphate", form: "Tablet", strength: "75 mg", category: "Antiplatelet", image: "/cloberry.jpg", rightImage: "/cloberry.jpg" },
  { id: 21, name: "Pentagard 40", composition: "Pantoprazole Sodium", form: "Delayed-release Capsule", strength: "40 mg", category: "PPI's", image: "/Pentagard.jpg", rightImage: "/Pentagard.jpg" },
  { id: 46, name: "Pentagard DSR", composition: "Pantoprazole Sodium 40mg + Domperidone 30mg", form: "Prolonged-release Capsule", strength: "40/30 mg", category: "PPI's", image: "/Pentagard-dsr.jpg", rightImage: "/Pentagard-dsr.jpg" },
  { id: 22, name: "Razed DSR", composition: "Rabeprazole Sodium 20mg + Domperidone 30mg", form: "Prolonged-release Capsule", strength: "20/30 mg", category: "PPI's", image: "/Razed.jpg", rightImage: "/Razed.jpg" },
  { id: 23, name: "Amoxberry-625", composition: "Amoxycillin & Potassium Clavulanate Tablets 1.2", form: "Tablet", strength: "500/125 mg", category: "Anti-Infective", image: "/Amoxberry.jpg", rightImage: "/Amoxberry.jpg" },
  { id: 24, name: "Cefropath-500", composition: "Cefuroxime Axetil", form: "Tablet", strength: "500 mg", category: "Anti-Infective", image: "/Cetropath.jpg", rightImage: "/Cetropath.jpg" },
  { id: 25, name: "Apserra", composition: "Aceclofenac 100mg +Paracetamol 325mg +Serratiopeptidase 15mg", form: "Tablet", strength: "100/325/15 mg", category: "Anti-Infective", image: "/Apserra.jpg", rightImage: "/Apserra.jpg" },
  { id: 26, name: "Vitzee Tablets", composition: " Super Anti-Oxidant + Multivitamin + Multiminerals", form: "Tablet", strength: "Complex", category: "Supplements", image: "/Vitzee.jpg", rightImage: "/Vitzee.jpg" },
  { id: 27, name: "Vitzee D3 60K", composition: "Cholecalciferol", form: "Tablet", strength: "60000 IU", category: "Supplements", image: "/Vitzee-D3-60K.jpg", rightImage: "/Vitzee-D3-60K.jpg" },
  { id: 28, name: "Cadcure", composition: "Methylcobalamin + Pyroxidine HCL + Alpha Lipoic Acid + Folic Acid + Vitamin D3 Tablets", form: "Tablet", strength: "Complex", category: "Supplements", image: "/Cadcure.jpg", rightImage: "/Cadcure.jpg" },
  { id: 29, name: "Preberry-NT", composition: "Pregabalin + Methylcobalamin + Nortriptyline ", form: "Tablet", strength: "Complex", category: "Supplements", image: "/Preberry-NT.jpg", rightImage: "/Preberry-NT.jpg" },
  { id: 30, name: "Calvance D", composition: "Calcium Citrate + Vit D3 + Magnesium Hydroxide + Zinc Sulphate Tablet", form: "Tablet", strength: "500/400 IU", category: "Supplements", image: "/Calvance-D.jpg", rightImage: "/Calvance-D.jpg" },
  { id: 31, name: "Calvance-DM", composition: "Calcium Carbonate IP (1250mg) eq. to elemental Calcium... 500mg Vitamin D3 IP. 2000 IU Methylcobalamin IP. 1500mcg L-Methylfolate Calcium USP. Img Pyridoxal-5 Phosphate.. 20mg", form: "Tablet", strength: "1250 mg~500 mg/2000IU/1500 mcg/20 mg", category: "Supplements", image: "/Calvance-DM.jpg", rightImage: "/Calvance-DM.jpg" },
  { id: 32, name: "Cosfur XT", composition: "Ferrous Ascorbate + Folic Acid + Elemental Iron", form: "Tablet", strength: "Complex", category: "Supplements", image: "/Cosfur-XT.jpg", rightImage: "/Cosfur-XT.jpg" },
]
